language: java
addons:
  sonarqube: true
jdk:
  - oraclejdk8
install:
  - mvn clean install
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.login=$SONAR_TOKEN
notifications:
  email: false
  slack:
    rooms:
      - secure: kI7GYBIbMVNI+NU9x14tJsMUyj09Np1voeRgqV91f6iwBgyoeD1DHEn1HRyapIaYbd2XJlNwqJ7qr3HZoh+S9JTQxux8I+UwfMWjTRcZIfDuWrZl1ydCnutV6i5NrP4yDWayTPEDxryNwVgSBPCOnC3F8a3BCzPHtMF9NtNgz2XcedavSNtaUAoZjjTc4Fe65Nn/gowGoU7t/W8dOhDqxDIkWqW03s1BICa0hG+LtCCjgCCYIOywFr+wyojbS7uBRtQ2YD9FAYTJn5cIZSFPNPScbGdD0ssT181lILHa2inIQqMSI0vMcb/9ZJ0eEl2O1putcwss6uHcX0fPS/DEkiodAkbqXWoQCFU63eupd/+oS5WgV74GOIZoLgN7pH+3dU+H8x8MPqulHIRQMBWWLUXb23iPiIp+ANj9vdfinkMXJ+cgXfG77GMcAmdNHBvWx+i4MDtN30LkmTx4O5/Pg88NTwLwHlK9uUbZvMegvSPQjBMuTmICYx2Qx/MylPwhdxPg744ropUnrDc89SaMdT00m23UN5+WQJO4UkI0hBExkyurxAnfFZUSWw6osD759WXnHpn4i+d+ROvpe0kgiJHEo8yxghXzl/yOoL5/Lc+KdDFWLhIoT+4y7NqQbcmmKfOkUqov2iGzE9XnophrpTZT3QTCAnhs4OoMR+PRf28=
    template:
      - "Build status: %{message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"